// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.22.0
// source: internal/transport/grpc/proto/auth.proto

package grpchandler

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Roles int32

const (
	Roles_ROLES_USER  Roles = 0
	Roles_ROLES_ADMIN Roles = 1 // ...
)

// Enum value maps for Roles.
var (
	Roles_name = map[int32]string{
		0: "ROLES_USER",
		1: "ROLES_ADMIN",
	}
	Roles_value = map[string]int32{
		"ROLES_USER":  0,
		"ROLES_ADMIN": 1,
	}
)

func (x Roles) Enum() *Roles {
	p := new(Roles)
	*p = x
	return p
}

func (x Roles) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Roles) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_transport_grpc_proto_auth_proto_enumTypes[0].Descriptor()
}

func (Roles) Type() protoreflect.EnumType {
	return &file_internal_transport_grpc_proto_auth_proto_enumTypes[0]
}

func (x Roles) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Roles.Descriptor instead.
func (Roles) EnumDescriptor() ([]byte, []int) {
	return file_internal_transport_grpc_proto_auth_proto_rawDescGZIP(), []int{0}
}

type SingInRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *SingInRequest) Reset() {
	*x = SingInRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_transport_grpc_proto_auth_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SingInRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SingInRequest) ProtoMessage() {}

func (x *SingInRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transport_grpc_proto_auth_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SingInRequest.ProtoReflect.Descriptor instead.
func (*SingInRequest) Descriptor() ([]byte, []int) {
	return file_internal_transport_grpc_proto_auth_proto_rawDescGZIP(), []int{0}
}

func (x *SingInRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *SingInRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type SingInResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccessToken  string `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken string `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
}

func (x *SingInResponse) Reset() {
	*x = SingInResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_transport_grpc_proto_auth_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SingInResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SingInResponse) ProtoMessage() {}

func (x *SingInResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transport_grpc_proto_auth_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SingInResponse.ProtoReflect.Descriptor instead.
func (*SingInResponse) Descriptor() ([]byte, []int) {
	return file_internal_transport_grpc_proto_auth_proto_rawDescGZIP(), []int{1}
}

func (x *SingInResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *SingInResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type SingUpRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string  `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Email    string  `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password string  `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Avatar   string  `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Roles    []Roles `protobuf:"varint,5,rep,packed,name=roles,proto3,enum=grpchandler.Roles" json:"roles,omitempty"`
}

func (x *SingUpRequest) Reset() {
	*x = SingUpRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_transport_grpc_proto_auth_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SingUpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SingUpRequest) ProtoMessage() {}

func (x *SingUpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transport_grpc_proto_auth_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SingUpRequest.ProtoReflect.Descriptor instead.
func (*SingUpRequest) Descriptor() ([]byte, []int) {
	return file_internal_transport_grpc_proto_auth_proto_rawDescGZIP(), []int{2}
}

func (x *SingUpRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *SingUpRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SingUpRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *SingUpRequest) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *SingUpRequest) GetRoles() []Roles {
	if x != nil {
		return x.Roles
	}
	return nil
}

type SingUpResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *SingUpResponse) Reset() {
	*x = SingUpResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_transport_grpc_proto_auth_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SingUpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SingUpResponse) ProtoMessage() {}

func (x *SingUpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transport_grpc_proto_auth_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SingUpResponse.ProtoReflect.Descriptor instead.
func (*SingUpResponse) Descriptor() ([]byte, []int) {
	return file_internal_transport_grpc_proto_auth_proto_rawDescGZIP(), []int{3}
}

func (x *SingUpResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_internal_transport_grpc_proto_auth_proto protoreflect.FileDescriptor

var file_internal_transport_grpc_proto_auth_proto_rawDesc = []byte{
	0x0a, 0x28, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x74, 0x72, 0x61, 0x6e, 0x73,
	0x70, 0x6f, 0x72, 0x74, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x61, 0x75, 0x74, 0x68, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x67, 0x72, 0x70, 0x63,
	0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x22, 0x47, 0x0a, 0x0d, 0x53, 0x69, 0x6e, 0x67, 0x49,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64,
	0x22, 0x58, 0x0a, 0x0e, 0x53, 0x69, 0x6e, 0x67, 0x49, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x23, 0x0a, 0x0d, 0x72, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68,
	0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x72, 0x65,
	0x66, 0x72, 0x65, 0x73, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x9f, 0x01, 0x0a, 0x0d, 0x53,
	0x69, 0x6e, 0x67, 0x55, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08,
	0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69,
	0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x1a,
	0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x76,
	0x61, 0x74, 0x61, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x76, 0x61, 0x74,
	0x61, 0x72, 0x12, 0x28, 0x0a, 0x05, 0x72, 0x6f, 0x6c, 0x65, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28,
	0x0e, 0x32, 0x12, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x2e,
	0x52, 0x6f, 0x6c, 0x65, 0x73, 0x52, 0x05, 0x72, 0x6f, 0x6c, 0x65, 0x73, 0x22, 0x20, 0x0a, 0x0e,
	0x53, 0x69, 0x6e, 0x67, 0x55, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x2a, 0x28,
	0x0a, 0x05, 0x52, 0x6f, 0x6c, 0x65, 0x73, 0x12, 0x0e, 0x0a, 0x0a, 0x52, 0x4f, 0x4c, 0x45, 0x53,
	0x5f, 0x55, 0x53, 0x45, 0x52, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x52, 0x4f, 0x4c, 0x45, 0x53,
	0x5f, 0x41, 0x44, 0x4d, 0x49, 0x4e, 0x10, 0x01, 0x32, 0x90, 0x01, 0x0a, 0x04, 0x41, 0x75, 0x74,
	0x68, 0x12, 0x43, 0x0a, 0x06, 0x53, 0x69, 0x6e, 0x67, 0x49, 0x6e, 0x12, 0x1a, 0x2e, 0x67, 0x72,
	0x70, 0x63, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x2e, 0x53, 0x69, 0x6e, 0x67, 0x49, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x68, 0x61,
	0x6e, 0x64, 0x6c, 0x65, 0x72, 0x2e, 0x53, 0x69, 0x6e, 0x67, 0x49, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x43, 0x0a, 0x06, 0x53, 0x69, 0x6e, 0x67, 0x55, 0x70,
	0x12, 0x1a, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x2e, 0x53,
	0x69, 0x6e, 0x67, 0x55, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x67,
	0x72, 0x70, 0x63, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x2e, 0x53, 0x69, 0x6e, 0x67, 0x55,
	0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0f, 0x5a, 0x0d, 0x2e,
	0x2f, 0x67, 0x72, 0x70, 0x63, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_transport_grpc_proto_auth_proto_rawDescOnce sync.Once
	file_internal_transport_grpc_proto_auth_proto_rawDescData = file_internal_transport_grpc_proto_auth_proto_rawDesc
)

func file_internal_transport_grpc_proto_auth_proto_rawDescGZIP() []byte {
	file_internal_transport_grpc_proto_auth_proto_rawDescOnce.Do(func() {
		file_internal_transport_grpc_proto_auth_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_transport_grpc_proto_auth_proto_rawDescData)
	})
	return file_internal_transport_grpc_proto_auth_proto_rawDescData
}

var file_internal_transport_grpc_proto_auth_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_transport_grpc_proto_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_internal_transport_grpc_proto_auth_proto_goTypes = []interface{}{
	(Roles)(0),             // 0: grpchandler.Roles
	(*SingInRequest)(nil),  // 1: grpchandler.SingInRequest
	(*SingInResponse)(nil), // 2: grpchandler.SingInResponse
	(*SingUpRequest)(nil),  // 3: grpchandler.SingUpRequest
	(*SingUpResponse)(nil), // 4: grpchandler.SingUpResponse
}
var file_internal_transport_grpc_proto_auth_proto_depIdxs = []int32{
	0, // 0: grpchandler.SingUpRequest.roles:type_name -> grpchandler.Roles
	1, // 1: grpchandler.Auth.SingIn:input_type -> grpchandler.SingInRequest
	3, // 2: grpchandler.Auth.SingUp:input_type -> grpchandler.SingUpRequest
	2, // 3: grpchandler.Auth.SingIn:output_type -> grpchandler.SingInResponse
	4, // 4: grpchandler.Auth.SingUp:output_type -> grpchandler.SingUpResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_transport_grpc_proto_auth_proto_init() }
func file_internal_transport_grpc_proto_auth_proto_init() {
	if File_internal_transport_grpc_proto_auth_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_transport_grpc_proto_auth_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SingInRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_transport_grpc_proto_auth_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SingInResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_transport_grpc_proto_auth_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SingUpRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_transport_grpc_proto_auth_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SingUpResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_transport_grpc_proto_auth_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_transport_grpc_proto_auth_proto_goTypes,
		DependencyIndexes: file_internal_transport_grpc_proto_auth_proto_depIdxs,
		EnumInfos:         file_internal_transport_grpc_proto_auth_proto_enumTypes,
		MessageInfos:      file_internal_transport_grpc_proto_auth_proto_msgTypes,
	}.Build()
	File_internal_transport_grpc_proto_auth_proto = out.File
	file_internal_transport_grpc_proto_auth_proto_rawDesc = nil
	file_internal_transport_grpc_proto_auth_proto_goTypes = nil
	file_internal_transport_grpc_proto_auth_proto_depIdxs = nil
}
